[logger]
level = "info"

[client]
showErrorDetails = false

[server]
headless = true
port = 8501
runOnSave = true

[theme]
primaryColor = "#80bfd4"
backgroundColor = "#1e232a"
secondaryBackgroundColor = "#101114"
textColor = "#ffffff"
font = "sans serif"
